---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Package and Deploy Bootable LAMP Image"
      solveButton: true

tabs:
  - name: ">_ terminal"
    url: /wetty
  - name: "bootc Documentation"
    url: https://containers.github.io/bootc/
    external: true
